#!/bin/bash

wget https://get.popcorntime.sh/build/Popcorn-Time-0.3.10-Linux-64.tar.xz -O popcorntime.tar.xz
sudo mkdir /opt/popcorntime
sudo tar Jxf popcorntime.tar.xz -C /opt/popcorntime
sudo ln -sf /opt/popcorntime/Popcorn-Time /usr/bin/Popcorn-Time
rm popcorntime.tar.xz

cd /opt/popcorntime/
./Popcorn-Time