#!/bin/bash

BC_OK=$(dpkg-query -W --showformat='${Status}\n' bc|grep "install ok installed")
if [ "" == "$BC_OK" ]
then
  sudo apt install bc
fi

FF_OK=$(dpkg-query -W --showformat='${Status}\n' ffmpeg|grep "install ok installed")
if [ "" == "$FF_OK" ]
then
  sudo apt install ffmpeg
fi

count=-1
function recursion {
  count=$(($count + 1))
  local file1=$1;

  for file in $file1/*
  do
  if [ -f "$file" ]
  then
  for (( i=1; i <= $count; i++ ))
  do
    printf "║ "
  done
  local filesize=$(stat -c%s "$file")
  filesize=$(echo "scale=4; $filesize / 1024 / 1024" | bc)
  local dateModify=$(date +"%d.%m.%Y в %H:%M" --reference="$file")
  local time=$(ffprobe \
    -v quiet  \
    -print_format ini  \
    -show_format  \
    "$file" | grep duration | sed s/duration=//)
  if [ -z "$time" ]
  then
    printf "╠═ ${file##*/}, ${filesize} MB, изменено ${dateModify}\n"
  else
    local timeMin=$(echo "scale=0; $time / 60" | bc);
    local timeSec=$(echo "scale=0; $time % 60" | bc);
    printf "╠═ ${file##*/}, ${filesize} MB, изменено ${dateModify}, ${timeMin} минут, ${timeSec} секунд\n"
  fi
  
  
  
  
  fi
  done
  
  for file in $file1/*
  do
  if [ -d "$file" ]
  then
  for (( i=1; i <= $count; i++ ))
  do
  printf "║ "
  done
  printf "║ ${file##*/}\n"
  recursion $file
  count=$(($count - 1))
  fi
  done
}
recursion $(pwd)
printf "Done.\n"